baseURL = "https://oxcarbazerpine.github.io/qingtaihugo/"
theme = "PaperMod"
languageCode = 'en-us'
title = 'Qingtai Site'
homeInfoParams = { Title = "欢迎来到 Qingtai 的博客", Content = "这里是内容摘要区" }
ShowPostList = true
